apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: lease-based-le-svc
  namespace: default
spec:
  selector:
    app: l-po
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8881
