apiVersion: apps/v1
kind: Deployment
metadata:
  name: l-po-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: l-po
  template:
    metadata:
      labels:
        app: l-po
    spec:
      serviceAccountName: lease-sa
      initContainers:
        - name: wait-for-redis
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup redis-service.default.svc.cluster.local; do sleep 1; done'] 
      containers:
      - image: lease-based-le
        name: l-po      
        resources: {}
        env:
          - name: IDENTIFIER
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"   
        imagePullPolicy: Never
        ports:
        - containerPort: 8881     

---
apiVersion: v1
kind: Service
metadata:
  name: lease-based-le-svc
  namespace: default
spec:
  selector:
    app: l-po
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8881
